version: '2'

services:
  db:
    image: mysql:5.6
    restart: always
    volumes:
       - /var/sentrifugo:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sentrifugo
  sentrifugo:
    build: .
    restart: always
    ports:
      - '8080:80'
      - '8443:443'
    depends_on:
      - db
    volumes:
      - '/var/sentrifugo:/dev/tty'
